In [7]:
import vaccontrib as vc
from vaccontrib.linalg import convert_2d_block_to_4d_matrix, convert_4d_matrix_to_2d_block
import numpy as np
from numpyarray_to_latex.jupyter import to_jup
from IPython.display import display, Math
import bfmplot as bp
import matplotlib.pyplot as pl
%matplotlib widget

In [8]:
%matplotlib widget

In [9]:
from vaccontrib.illustration import get_circular_vector_and_matrix_presentation

Chom = vc.covid.get_homogeneous_contribution_matrix_covid([6.,6.],'delta',)
C = vc.covid.get_reduced_vaccinated_susceptible_contribution_matrix_covid([6.,6,6,6,6],variant='delta')
K = vc.covid.get_next_generation_matrix_covid([6.,6,6,6,6],variant='delta')
y = vc.get_eigenvector(K)
y = y.sum(axis=0)
y = np.array([y[0],y[1:].sum()])
#C = get_homogeneous_contribution_matrix('alpha',[4.,4.])
#print(C)
#C = np.arange(9).reshape(3,3)[::-1,:]

ax = get_circular_vector_and_matrix_presentation(y, Chom).plot()
ax.set_xlim(-1.5,7)
ax.axis('off')
joined2 = get_circular_vector_and_matrix_presentation(y, C)
ax = joined2.plot()
ax.set_xlim(-1.5,7)
ax.axis('off')
ax.get_figure().savefig('delta_example_no_lockdown.pdf')
#ax = plot_reduced_contribution_matrix_stacked(Chom)
#ax = plot_reduced_contribution_matrix(C,0.6)
#ax = plot_reduced_contribution_matrix_stacked(C)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [23]:
x, y = joined2.cap0.exterior.xy
ndx = np.where(np.diff(y)==0)[0][0]
y[ndx], y[ndx+1]
x[ndx], x[ndx+1]

(0.9146841872240591, -0.914684187224059)

In [26]:
from vaccontrib.illustration import get_circular_vector_and_matrix_presentation

Chom = vc.covid.get_homogeneous_contribution_matrix_covid([1.,4.],'alpha',)
Cred = vc.covid.get_reduced_vaccinated_susceptible_contribution_matrix_covid([1.,4,4,4,4],variant='alpha')
C = vc.covid.get_contribution_matrix_covid([1.,4,4,4,4],variant='alpha')
K = vc.covid.get_next_generation_matrix_covid([1.,4,4,4,4],variant='alpha')
y = vc.get_eigenvector(K)
yred = y.sum(axis=0)
yred = np.array([yred[0],yred[1:].sum()])
#C = get_homogeneous_contribution_matrix('alpha',[4.,4.])
#print(C)
#C = np.arange(9).reshape(3,3)[::-1,:]
yhom = vc.covid.get_homogeneous_eigenvector_covid(variant='alpha')
ax = get_circular_vector_and_matrix_presentation(yhom, Chom).plot()
ax.set_xlim(-1.5,7)
ax.axis('off')

ax = get_circular_vector_and_matrix_presentation(yred, Cred).plot()
ax.set_xlim(-1.5,7)
ax.axis('off')

#ax = plot_reduced_contribution_matrix_stacked(Chom)
#ax = plot_reduced_contribution_matrix(C,0.6)
#ax = plot_reduced_contribution_matrix_stacked(C)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(-1.5, 7.0, -1.1, 1.1)

In [9]:
to_jup(Cred.sum(axis=1)/Cred.sum())
to_jup(yred/yred.sum())
to_jup(Chom.sum(axis=1)/Chom.sum())
to_jup(yhom/yhom.sum())


<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [10]:
C.sum()

0.5752426884313784

In [11]:
ynext = vc.linalg.convert_4d_matrix_to_2d_block(K).dot(y.flatten())
ynext /= ynext.sum()
ynext.reshape(4,5).sum(axis=0)

array([0.89230793, 0.03017644, 0.0535565 , 0.00755762, 0.01640151])

In [12]:
y.sum(axis=0)

array([0.89230793, 0.03017644, 0.0535565 , 0.00755762, 0.01640151])

In [13]:
ynext_from_C = C.sum(axis=-1).sum(axis=-2)
print(ynext_from_C)
ynext_from_C /= ynext_from_C.sum()
ynext_from_C.sum(axis=0)

[[0.10872846 0.         0.         0.         0.        ]
 [0.15901979 0.         0.00330056 0.         0.        ]
 [0.22865367 0.0143095  0.02267542 0.00358378 0.0077775 ]
 [0.0168917  0.00304927 0.004832   0.00076368 0.00165734]]


array([0.89230793, 0.03017644, 0.0535565 , 0.00755762, 0.01640151])

In [14]:
ynext = vc.linalg.convert_4d_matrix_to_2d_block(K).dot(y.flatten())
ynext.sum()

0.5752426884313783

In [15]:
C.sum()

0.5752426884313784

In [16]:
Chom.sum()

0.5480582320692857

In [17]:
Khom = get_homogeneous_next_generation_matrix('alpha',[1.,4.])
Chom = get_homogeneous_contribution_matrix('alpha',[1.,4.])
yhom = get_homogeneous_eigenvector('alpha')
print(Khom.dot(yhom)/Khom.dot(yhom).sum())
print(yhom)

[0.85583015 0.14416985]
[0.85583015 0.14416985]


In [18]:
Khom.dot(np.diag(yhom))

array([[0.35084183, 0.11820293],
       [0.05910146, 0.01991201]])

In [19]:
Chom

array([[0.35084183, 0.11820293],
       [0.05910146, 0.01991201]])

In [20]:
R, y = vc.linalg.get_spectral_radius_and_eigenvector(Khom)

In [21]:
R

0.5480582320692857

In [22]:
y

array([0.85583015, 0.14416985])

In [23]:
yhom

array([0.85583015, 0.14416985])

In [24]:
Chom.sum()

0.5480582320692857